"use client";
import { useEffect, useState } from "react";
import type { Bid, Opportunity, Role } from "@edurev/types";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
const api=process.env.NEXT_PUBLIC_API_URL??"http://localhost:4000/api";
export function BidDesk({opportunity}:{opportunity:Opportunity}){const [role,setRole]=useState<Role>("STUDENT"),[bids,setBids]=useState<Bid[]>([]),[message,setMessage]=useState(""),[state,setState]=useState<"idle"|"loading"|"success"|"error">("idle"),[amount,setAmount]=useState(String(opportunity.budget)),[days,setDays]=useState("7 days"),[skills,setSkills]=useState(""),[notice,setNotice]=useState("");const studentId="stu-202";const mine=bids.some(b=>b.studentId===studentId);
const load=async()=>{try{const r=await fetch(`${api}/opportunities/${opportunity.id}/bids`);const j=await r.json();setBids(j.data??[])}catch{setNotice("Bids are unavailable until the API is running.")}};useEffect(()=>{load()},[opportunity.id]);
const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!amount||!days||!message||!skills){setState("error");setNotice("Complete every bid field.");return}setState("loading");try{const r=await fetch(`${api}/opportunities/${opportunity.id}/bids`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({studentId,proposedAmount:Number(amount),estimatedCompletionTime:days,message,relevantSkills:skills})});const j=await r.json();if(!r.ok)throw new Error(j.message);setBids(x=>[...x,j.data]);setState("success");setNotice("Bid submitted successfully.")}catch(e){setState("error");setNotice(e instanceof Error?e.message:"Unable to submit bid.")}};
const allocate=async(id:string)=>{setState("loading");try{const r=await fetch(`${api}/opportunities/${opportunity.id}/allocate`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({studentId:id,allocatedBy:role})});const j=await r.json();if(!r.ok)throw new Error(j.message);setState("success");setNotice(`Opportunity allocated to ${id}.`)}catch(e){setState("error");setNotice(e instanceof Error?e.message:"Allocation blocked.")}};
return <Card className="p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold text-slate-950">Bid desk</h2><p className="text-sm text-slate-500">Demo role controls conditional UI only.</p></div><select aria-label="Demo role" className="rounded-lg border border-slate-200 px-3 py-2 text-sm" onChange={e=>setRole(e.target.value as Role)} value={role}><option value="STUDENT">Student</option><option value="BID_DESK_ANALYST">Bid Desk Analyst</option><option value="FACULTY_DIRECTOR">Faculty Director</option></select></div>{notice&&<p className={`mt-4 rounded-lg px-3 py-2 text-sm ${state==="error"?"bg-rose-50 text-rose-700":"bg-emerald-50 text-emerald-700"}`}>{notice}</p>}{role==="STUDENT"?<form className="mt-5 grid gap-3" onSubmit={submit}>{mine?<p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-800">You have already submitted a bid for this opportunity.</p>:<><input className="rounded-lg border p-2" min="1" onChange={e=>setAmount(e.target.value)} placeholder="Proposed amount" type="number" value={amount}/><input className="rounded-lg border p-2" onChange={e=>setDays(e.target.value)} placeholder="Estimated completion time" value={days}/><input className="rounded-lg border p-2" onChange={e=>setSkills(e.target.value)} placeholder="Relevant skills / experience" value={skills}/><textarea className="rounded-lg border p-2" onChange={e=>setMessage(e.target.value)} placeholder="Student message" value={message}/><Button disabled={state==="loading"} type="submit"> {state==="loading"?"Submitting…":"Submit bid"}</Button></>}</form>:<div className="mt-5 space-y-3">{bids.length?bids.map(b=><div className="rounded-lg border p-3 text-sm" key={b.id}><b>{b.studentId}</b> · ₹{b.proposedAmount}<p className="mt-1 text-slate-600">{b.relevantSkills}</p>{role==="BID_DESK_ANALYST"&&<Button className="mt-2" disabled={state==="loading"} onClick={()=>allocate(b.studentId)}>Allocate after eligibility check</Button>}</div>):<p className="text-sm text-slate-500">No bids yet.</p>}</div>}</Card>}
