import cors from "cors"; import express from "express";
import { academicSnapshots, allocate, analytics, blackouts, checkSafeguards, dashboardMetrics, earnings, getBids, getOpportunity, getStudent, getStudentTier, hasBid, hourLogs, opportunities, platformAccounts, proposals, safeguards, settings, students, submitBid, trainingModules, verifyEarning } from "@edurev/mock-data";
const error=(res:express.Response,message:string,status=400)=>res.status(status).json({message});
export function createApp(){const app=express();app.use(cors({origin:process.env.WEB_ORIGIN??"http://localhost:3000"}));app.use(express.json());
app.get("/api/health",(_,r)=>r.json({status:"ok",service:"edurev-api"}));
app.get("/api/dashboard",(_,r)=>r.json({metrics:dashboardMetrics,recentOpportunities:opportunities.slice(0,3)}));
app.get("/api/opportunities",(_,r)=>r.json({data:opportunities})); app.get("/api/opportunities/:id",(q,r)=>{const x=getOpportunity(q.params.id);return x?r.json({data:x}):error(r,"Opportunity not found.",404)});
app.get("/api/opportunities/:id/bids",(q,r)=>r.json({data:getBids(q.params.id)}));
app.post("/api/opportunities/:id/bids",(q,r)=>{const {studentId,proposedAmount,estimatedCompletionTime,message,relevantSkills}=q.body; if(!getOpportunity(q.params.id))return error(r,"Opportunity not found.",404);if(!studentId||!proposedAmount||!estimatedCompletionTime||!message||!relevantSkills)return error(r,"All bid fields are required.");if(hasBid(q.params.id,studentId))return error(r,"You have already submitted a bid for this opportunity.",409);try{return r.status(201).json({data:submitBid({opportunityId:q.params.id,studentId,proposedAmount:Number(proposedAmount),estimatedCompletionTime,message,relevantSkills})})}catch(e){return error(r,e instanceof Error?e.message:"Unable to submit bid.")}});
app.post("/api/opportunities/:id/allocate",(q,r)=>{const {studentId,allocatedBy="BID_DESK_ANALYST"}=q.body; if(!studentId)return error(r,"studentId is required.");try{return r.json({data:allocate(q.params.id,studentId,allocatedBy)})}catch(e){return error(r,e instanceof Error?e.message:"Unable to allocate.")}});
app.get("/api/students",(_,r)=>r.json({data:students})); app.get("/api/students/:id",(q,r)=>{const x=getStudent(q.params.id);return x?r.json({data:x}):error(r,"Student not found.",404)});app.get("/api/students/:id/tier",(q,r)=>{const x=getStudentTier(q.params.id);return x?r.json({data:x}):error(r,"Student not found.",404)});app.get("/api/students/:id/training",(q,r)=>r.json({data:trainingModules[q.params.id]??[]}));
app.get("/api/earnings",(q,r)=>{const id=q.query.studentId as string|undefined; r.json({data:id?earnings.filter(x=>x.studentId===id):earnings})});app.post("/api/earnings",(q,r)=>r.status(201).json({data:q.body,note:"Mock endpoint: persistence will be added with the database."}));app.patch("/api/earnings/:id/verify",(q,r)=>{try{return r.json({data:verifyEarning(q.params.id,q.body.verifiedBy??"FACULTY_DIRECTOR",q.body.status??"VERIFIED")})}catch(e){return error(r,e instanceof Error?e.message:"Not found.",404)}});app.get("/api/platform-accounts",(_,r)=>r.json({data:platformAccounts}));
app.get("/api/safeguards",(_,r)=>r.json({data:safeguards}));app.get("/api/safeguards/:studentId",(q,r)=>r.json({data:checkSafeguards(q.params.studentId)}));app.get("/api/hours/:studentId",(q,r)=>{const x=hourLogs.find(x=>x.studentId===q.params.studentId);return x?r.json({data:x}):error(r,"Hour log not found.",404)});app.post("/api/hours",(q,r)=>r.status(201).json({data:q.body,note:"Mock hour log accepted."}));app.get("/api/blackouts",(_,r)=>r.json({data:blackouts}));app.post("/api/safeguards/hour-cap/override",(q,r)=>{if(!q.body.reason||q.body.role!=="FACULTY_DIRECTOR")return error(r,"A Faculty Director reason is required.");const x=hourLogs.find(x=>x.studentId===q.body.studentId);if(x){x.status="WARNING";x.overridden=true;x.remainingHours=1;}return r.json({data:x,approvedBy:"FACULTY_DIRECTOR",timestamp:new Date().toISOString()})});
app.get("/api/analytics",(_,r)=>r.json({data:analytics}));app.get("/api/proposals",(_,r)=>r.json({data:proposals}));app.get("/api/settings",(_,r)=>r.json({data:settings}));app.get("/api/academic/:studentId",(q,r)=>r.json({data:academicSnapshots.find(x=>x.studentId===q.params.studentId)}));app.use((_,r)=>error(r,"Route not found.",404));return app;}
