import type { AcademicSnapshot, Allocation, AnalyticsSnapshot, Bid, BlackoutPeriod, DashboardMetrics, EarningsEntry, HourLog, Opportunity, PlatformAccount, Proposal, Safeguard, SafeguardCheck, SettingsSummary, Student, Tier, TierSummary, TrainingModule } from "@edurev/types";
export const tierRank:Record<Tier,number>={TIER_1:1,TIER_2:2,TIER_3:3,TIER_4:4};
export const opportunities:Opportunity[]=[
{id:"opp-1024",title:"Student success dashboard",project:"Student success dashboard",client:"Northstar Labs",company:"Northstar Labs",description:"Design a learner progress dashboard.",category:"Product design",skills:["Figma","Research"],budget:18000,currency:"INR",deadline:"2026-09-20",status:"OPEN",requiredTier:"TIER_2",estimatedHours:18,numberOfBids:0,slaDeadline:"2026-09-14T22:00:00.000Z",matchScore:94,deliverables:["Research","Flows","Handoff"],updatedAt:"2026-09-12"},
{id:"opp-1025",title:"Campaign analytics refresh",project:"Campaign analytics refresh",client:"Owl & Oak",company:"Owl & Oak",description:"Build an executive reporting view.",category:"Data analysis",skills:["Excel","SQL"],budget:12500,currency:"INR",deadline:"2026-09-24",status:"UNDER_REVIEW",requiredTier:"TIER_2",estimatedHours:14,numberOfBids:1,slaDeadline:"2026-09-15T18:00:00.000Z",matchScore:89,deliverables:["Audit","Dashboard"],updatedAt:"2026-09-13"},
{id:"opp-1026",title:"Content operations playbook",project:"Content operations playbook",client:"Juniper Health",company:"Juniper Health",description:"Create an editorial workflow.",category:"Content strategy",skills:["Writing","Notion"],budget:9000,currency:"INR",deadline:"2026-09-28",status:"OPEN",requiredTier:"TIER_1",estimatedHours:10,numberOfBids:0,slaDeadline:"2026-09-16T18:00:00.000Z",matchScore:82,deliverables:["Audit","Calendar"],updatedAt:"2026-09-13"}];
export const students:Student[]=[
{id:"stu-201",name:"Maya Chen",email:"maya.chen@example.com",avatarInitials:"MC",program:"Product Design",course:"B.Des",year:3,tier:"TIER_3",status:"ACTIVE",skills:["Figma","Research","Prototyping"],trainingProgress:91,progress:91,cgpa:8.2,joinedAt:"2026-03-14",projectsCompleted:7,earnings:8320,mentor:"Elena Martin"},
{id:"stu-202",name:"Rohan Patel",email:"rohan.patel@example.com",avatarInitials:"RP",program:"Data Analytics",course:"B.Tech",year:3,tier:"TIER_2",status:"ACTIVE",skills:["Excel","SQL","Power BI"],trainingProgress:68,progress:68,cgpa:7.8,joinedAt:"2026-05-02",projectsCompleted:4,earnings:0,mentor:"Elena Martin"},
{id:"stu-203",name:"Amara Okafor",email:"amara.okafor@example.com",avatarInitials:"AO",program:"Content Strategy",course:"BBA",year:2,tier:"TIER_2",status:"ACTIVE",skills:["Writing","SEO"],trainingProgress:46,progress:46,cgpa:6.4,joinedAt:"2026-06-18",projectsCompleted:2,earnings:0,mentor:"Jordan Lee"}];
export const trainingModules:Record<string,TrainingModule[]>={"stu-201":[{id:"tm1",title:"UX Research",description:"Interview and synthesis",status:"COMPLETED",completionPercentage:100},{id:"tm2",title:"Portfolio",description:"Case study",status:"IN_PROGRESS",completionPercentage:82}],"stu-202":[{id:"tm3",title:"SQL Foundations",description:"Queries",status:"COMPLETED",completionPercentage:100},{id:"tm4",title:"Dashboarding",description:"Reporting",status:"IN_PROGRESS",completionPercentage:68}],"stu-203":[{id:"tm5",title:"Content Strategy",description:"Editorial planning",status:"IN_PROGRESS",completionPercentage:46}]};
export const bids:Bid[]=[{id:"bid-1",opportunityId:"opp-1025",studentId:"stu-202",proposedAmount:12000,estimatedCompletionTime:"10 days",message:"I can turn channel data into an actionable report.",relevantSkills:"SQL, Power BI",status:"SUBMITTED",createdAt:"2026-09-13"}];
export const allocations:Allocation[]=[];
export const earnings=Object.assign([{id:"earn-1",studentId:"stu-201",platformName:"Freelance marketplace",originalAmount:100,originalCurrency:"USD",exchangeRate:83.2,convertedAmount:8320,convertedCurrency:"INR",earningDate:"2026-09-08",verificationStatus:"PENDING" as const,evidence:"Invoice screenshot",evidenceStatus:"AVAILABLE" as const,createdAt:"2026-09-08"}] as EarningsEntry[],{period:"September 2026",gross:8320,platformFees:0,net:8320,change:12.4});
export const platformAccounts:PlatformAccount[]=[{id:"pa-1",studentId:"stu-201",platform:"Freelance marketplace",accountIdentifier:"maya_design",accountStatus:"ACTIVE",verificationStatus:"VERIFIED"}];
export const academicSnapshots:AcademicSnapshot[]=[{studentId:"stu-201",cgpa:8.2,requiredCgpa:7,cgpaStatus:"ELIGIBLE",complianceStatus:"COMPLIANT"},{studentId:"stu-202",cgpa:7.8,requiredCgpa:7,cgpaStatus:"ELIGIBLE",complianceStatus:"COMPLIANT"},{studentId:"stu-203",cgpa:6.4,requiredCgpa:7,cgpaStatus:"RESTRICTED",complianceStatus:"WARNING"}];
export const hourLogs:HourLog[]=[{studentId:"stu-201",period:"2026-W37",allowedHours:20,loggedHours:12,remainingHours:8,status:"NORMAL"},{studentId:"stu-202",period:"2026-W37",allowedHours:20,loggedHours:20,remainingHours:0,status:"BLOCKED"},{studentId:"stu-203",period:"2026-W37",allowedHours:20,loggedHours:14,remainingHours:6,status:"WARNING"}];
export const blackouts:BlackoutPeriod[]=[{id:"blackout-1",title:"Semester examinations",startDate:"2026-12-10",endDate:"2026-12-20"}];
export const safeguards:Safeguard[]=[{id:"safe-1",name:"Hour Cap",description:"Weekly work hours are capped.",status:"healthy",owner:"Faculty",lastCheckedAt:"2026-09-13"},{id:"safe-2",name:"CGPA Gate",description:"Minimum CGPA is required.",status:"attention",owner:"Academic cell",lastCheckedAt:"2026-09-13"},{id:"safe-3",name:"Exam Blackout",description:"New work is blocked during exams.",status:"healthy",owner:"Academic calendar",lastCheckedAt:"2026-09-13"}];
export const proposals:Proposal[]=[{id:"pro-1",title:"Dashboard discovery plan",studentName:"Maya Chen",opportunityId:"opp-1024",author:"Maya Chen",status:"IN_REVIEW",reviewStatus:"PENDING",version:1,submittedAt:"2026-09-12",value:18000}];
export const settings:SettingsSummary={organizationName:"EduRev Studio",notificationEmail:"operations@edurev.example",weeklyDigestEnabled:true,timezone:"Asia/Kolkata"};
export const analytics:AnalyticsSnapshot={placementRate:72,proposalWinRate:38,averageResponseHours:18,learnerSatisfaction:4.7,weeklyActivity:[{label:"Mon",value:42},{label:"Tue",value:65},{label:"Wed",value:54},{label:"Thu",value:78},{label:"Fri",value:61}],studentsByTier:[{tier:"TIER_1",count:24},{tier:"TIER_2",count:61},{tier:"TIER_3",count:32},{tier:"TIER_4",count:11}]};
export const dashboardMetrics:DashboardMetrics={activeStudents:3,opportunityPipeline:3,monthlyEarnings:8320,completionRate:68,totalBids:1,allocations:0,verifiedEarnings:0,complianceRate:67};
export const getOpportunity=(id:string)=>opportunities.find(x=>x.id===id); export const getStudent=(id:string)=>students.find(x=>x.id===id);
export const getStudentTier=(id:string):TierSummary|undefined=>{const s=getStudent(id);if(!s)return;const next=(tierRank[s.tier]<4?(`TIER_${tierRank[s.tier]+1}` as Tier):null);return {studentId:id,currentTier:s.tier,nextTier:next,progressToNextTier:s.trainingProgress,completedTraining:s.projectsCompleted,requirements:[{label:"Complete training modules",completed:s.trainingProgress>=60},{label:"Meet academic eligibility",completed:s.cgpa>=7},{label:"Complete portfolio work",completed:s.projectsCompleted>=3}]};};
export const getBids=(id:string)=>bids.filter(x=>x.opportunityId===id); export const hasBid=(op:string,student:string)=>bids.some(x=>x.opportunityId===op&&x.studentId===student);
export function submitBid(input:Omit<Bid,"id"|"status"|"createdAt">){if(hasBid(input.opportunityId,input.studentId))throw new Error("You have already submitted a bid for this opportunity.");const bid={...input,id:`bid-${bids.length+1}`,status:"SUBMITTED" as const,createdAt:new Date().toISOString()};bids.push(bid);const o=getOpportunity(input.opportunityId);if(o){o.numberOfBids++;o.status="UNDER_REVIEW";}return bid;}
export function checkSafeguards(studentId:string,opportunityId?:string):SafeguardCheck{const s=getStudent(studentId)!;const h=hourLogs.find(x=>x.studentId===studentId)!;const a=academicSnapshots.find(x=>x.studentId===studentId)!;const o=opportunityId?getOpportunity(opportunityId):undefined;const blackout=blackouts.some(b=>new Date()>=new Date(b.startDate)&&new Date()<=new Date(b.endDate));const tier=!o||tierRank[s.tier]>=tierRank[o.requiredTier];const reasons:string[]=[];if(!tier)reasons.push("Student tier does not meet the opportunity requirement.");if(a.cgpaStatus!=="ELIGIBLE")reasons.push("CGPA eligibility is restricted.");if(h.status==="BLOCKED")reasons.push("Weekly work-hour limit reached.");if(blackout)reasons.push("Exam blackout is active.");if(a.complianceStatus==="NON_COMPLIANT")reasons.push("Compliance requirements are incomplete.");return {studentId,tierEligible:tier,cgpaEligible:a.cgpaStatus==="ELIGIBLE",hourEligible:h.status!=="BLOCKED",blackoutEligible:!blackout,complianceEligible:a.complianceStatus!=="NON_COMPLIANT",eligible:reasons.length===0,reasons};}
export function allocate(opportunityId:string,studentId:string,allocatedBy:string){const check=checkSafeguards(studentId,opportunityId);if(!check.eligible)throw new Error(check.reasons.join(" "));const o=getOpportunity(opportunityId);if(!o)throw new Error("Opportunity not found.");o.status="ALLOCATED";o.allocatedStudentId=studentId;const allocation={opportunityId,studentId,allocatedBy,allocatedAt:new Date().toISOString(),status:"ALLOCATED" as const};allocations.push(allocation);return allocation;}
export function verifyEarning(id:string,verifiedBy:string,status:"VERIFIED"|"REJECTED"){const e=earnings.find(x=>x.id===id);if(!e)throw new Error("Earning not found.");e.verificationStatus=status;e.verifiedBy=verifiedBy;e.verifiedAt=new Date().toISOString();return e;}
